/**
 * components/leads/mock-data.ts
 *
 * Realistic mock leads for frontend development and demo purposes.
 * Replace with real Supabase data fetching when backend is connected.
 */
import type { LeadRow } from './types'

const NOW = new Date()
const daysAgo = (d: number) => new Date(NOW.getTime() - d * 86400000).toISOString()
const hoursAgo = (h: number) => new Date(NOW.getTime() - h * 3600000).toISOString()

export const MOCK_BATCHES = [
  { id: 'b1', name: 'Q2 SaaS Founders',    leadCount: 124 },
  { id: 'b2', name: 'Inbound — March 2026', leadCount: 56  },
  { id: 'b3', name: 'Cold Outreach v1',     leadCount: 212 },
  { id: 'b4', name: 'Series A Companies',   leadCount: 88  },
]

export const MOCK_TEAM = [
  { id: 'u1', name: 'Alice Chen',   email: 'alice@acme.co' },
  { id: 'u2', name: 'Bob Tanaka',   email: 'bob@acme.co'   },
  { id: 'u3', name: 'Cara O\'Brien', email: 'cara@acme.co'  },
]

export const MOCK_LEADS: LeadRow[] = [
  {
    id: 'l01', workspace_id: 'ws1',
    first_name: 'James', last_name: 'Harrington', email: 'james.h@vertexsoftware.io',
    phone: '+1 415 555 0101', company: 'Vertex Software', title: 'CEO',
    website: 'https://vertexsoftware.io', linkedin_url: 'https://linkedin.com/in/jharrington',
    status: 'interested', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: hoursAgo(2), created_at: daysAgo(14), updated_at: hoursAgo(2),
  },
  {
    id: 'l02', workspace_id: 'ws1',
    first_name: 'Sofia', last_name: 'Müller', email: 'sofia@cloudnine.de',
    phone: '+49 89 555 0202', company: 'CloudNine GmbH', title: 'VP Engineering',
    website: 'https://cloudnine.de', linkedin_url: null,
    status: 'replied', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'csv_import',
    last_activity_at: hoursAgo(5), created_at: daysAgo(12), updated_at: hoursAgo(5),
  },
  {
    id: 'l03', workspace_id: 'ws1',
    first_name: 'Marcus', last_name: 'Osei', email: 'marcus@scalehq.com',
    phone: null, company: 'ScaleHQ', title: 'Founder',
    website: 'https://scalehq.com', linkedin_url: 'https://linkedin.com/in/marcosei',
    status: 'contacted', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: daysAgo(1), created_at: daysAgo(10), updated_at: daysAgo(1),
  },
  {
    id: 'l04', workspace_id: 'ws1',
    first_name: 'Priya', last_name: 'Nair', email: 'priya@loopanalytics.in',
    phone: '+91 98 555 0404', company: 'Loop Analytics', title: 'CTO',
    website: null, linkedin_url: 'https://linkedin.com/in/priya-nair',
    status: 'new', batch_id: 'b2', batch_name: 'Inbound — March 2026',
    assigned_to: 'u3', assigned_name: "Cara O'Brien", source: 'manual',
    last_activity_at: daysAgo(2), created_at: daysAgo(9), updated_at: daysAgo(2),
  },
  {
    id: 'l05', workspace_id: 'ws1',
    first_name: 'Lucas', last_name: 'Fontaine', email: 'lucas@growthloop.fr',
    phone: '+33 1 55 50 0505', company: 'GrowthLoop', title: 'Head of Sales',
    website: 'https://growthloop.fr', linkedin_url: null,
    status: 'converted', batch_id: 'b3', batch_name: 'Cold Outreach v1',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'csv_import',
    last_activity_at: hoursAgo(18), created_at: daysAgo(20), updated_at: hoursAgo(18),
  },
  {
    id: 'l06', workspace_id: 'ws1',
    first_name: 'Yuki', last_name: 'Tanabe', email: 'y.tanabe@nexusai.jp',
    phone: '+81 3 555 0606', company: 'NexusAI', title: 'CEO',
    website: 'https://nexusai.jp', linkedin_url: 'https://linkedin.com/in/yukitanabe',
    status: 'interested', batch_id: 'b4', batch_name: 'Series A Companies',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: hoursAgo(8), created_at: daysAgo(7), updated_at: hoursAgo(8),
  },
  {
    id: 'l07', workspace_id: 'ws1',
    first_name: 'Amara', last_name: 'Diallo', email: 'amara@finbridge.ng',
    phone: null, company: 'FinBridge Africa', title: 'Co-Founder',
    website: 'https://finbridge.ng', linkedin_url: null,
    status: 'not_interested', batch_id: 'b3', batch_name: 'Cold Outreach v1',
    assigned_to: 'u3', assigned_name: "Cara O'Brien", source: 'csv_import',
    last_activity_at: daysAgo(5), created_at: daysAgo(22), updated_at: daysAgo(5),
  },
  {
    id: 'l08', workspace_id: 'ws1',
    first_name: 'Ethan', last_name: 'Brooks', email: 'ethan@datastride.com',
    phone: '+1 212 555 0808', company: 'DataStride', title: 'CPO',
    website: 'https://datastride.com', linkedin_url: 'https://linkedin.com/in/ethanbrooks',
    status: 'replied', batch_id: 'b4', batch_name: 'Series A Companies',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'csv_import',
    last_activity_at: hoursAgo(12), created_at: daysAgo(6), updated_at: hoursAgo(12),
  },
  {
    id: 'l09', workspace_id: 'ws1',
    first_name: 'Isabelle', last_name: 'Vance', email: 'ivance@shipfast.io',
    phone: '+1 628 555 0909', company: 'ShipFast', title: 'VP Product',
    website: 'https://shipfast.io', linkedin_url: null,
    status: 'new', batch_id: 'b2', batch_name: 'Inbound — March 2026',
    assigned_to: null, assigned_name: null, source: 'manual',
    last_activity_at: null, created_at: daysAgo(3), updated_at: daysAgo(3),
  },
  {
    id: 'l10', workspace_id: 'ws1',
    first_name: 'Noah', last_name: 'Kim', email: 'noah.kim@helixdata.co',
    phone: '+82 2 555 1010', company: 'HelixData', title: 'CTO',
    website: 'https://helixdata.co', linkedin_url: 'https://linkedin.com/in/noah-kim',
    status: 'contacted', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: daysAgo(3), created_at: daysAgo(15), updated_at: daysAgo(3),
  },
  {
    id: 'l11', workspace_id: 'ws1',
    first_name: 'Chen', last_name: 'Wei', email: 'chenwei@pivotcrm.cn',
    phone: null, company: 'PivotCRM', title: 'CEO',
    website: null, linkedin_url: null,
    status: 'unsubscribed', batch_id: 'b3', batch_name: 'Cold Outreach v1',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'csv_import',
    last_activity_at: daysAgo(10), created_at: daysAgo(30), updated_at: daysAgo(10),
  },
  {
    id: 'l12', workspace_id: 'ws1',
    first_name: 'Diana', last_name: 'Petrov', email: 'diana@stackwave.eu',
    phone: '+7 495 555 1212', company: 'StackWave', title: 'COO',
    website: 'https://stackwave.eu', linkedin_url: 'https://linkedin.com/in/diana-petrov',
    status: 'interested', batch_id: 'b4', batch_name: 'Series A Companies',
    assigned_to: 'u3', assigned_name: "Cara O'Brien", source: 'csv_import',
    last_activity_at: hoursAgo(3), created_at: daysAgo(8), updated_at: hoursAgo(3),
  },
  {
    id: 'l13', workspace_id: 'ws1',
    first_name: 'Ravi', last_name: 'Patel', email: 'ravi@launchpad.in',
    phone: '+91 22 555 1313', company: 'LaunchPad', title: 'Founder',
    website: 'https://launchpad.in', linkedin_url: null,
    status: 'new', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: null, created_at: daysAgo(1), updated_at: daysAgo(1),
  },
  {
    id: 'l14', workspace_id: 'ws1',
    first_name: 'Layla', last_name: 'Hassan', email: 'layla@orbitcloud.ae',
    phone: '+971 4 555 1414', company: 'OrbitCloud', title: 'CTO',
    website: 'https://orbitcloud.ae', linkedin_url: 'https://linkedin.com/in/laylahassan',
    status: 'do_not_contact', batch_id: 'b3', batch_name: 'Cold Outreach v1',
    assigned_to: null, assigned_name: null, source: 'csv_import',
    last_activity_at: daysAgo(20), created_at: daysAgo(40), updated_at: daysAgo(20),
  },
  {
    id: 'l15', workspace_id: 'ws1',
    first_name: 'Tom', last_name: 'Whittaker', email: 'tom@buildwise.co.uk',
    phone: '+44 20 7946 1515', company: 'BuildWise', title: 'VP Sales',
    website: 'https://buildwise.co.uk', linkedin_url: null,
    status: 'contacted', batch_id: 'b2', batch_name: 'Inbound — March 2026',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'manual',
    last_activity_at: daysAgo(4), created_at: daysAgo(18), updated_at: daysAgo(4),
  },
  {
    id: 'l16', workspace_id: 'ws1',
    first_name: 'Mei', last_name: 'Ling', email: 'mei@appvault.sg',
    phone: '+65 9 555 1616', company: 'AppVault', title: 'CEO',
    website: 'https://appvault.sg', linkedin_url: 'https://linkedin.com/in/meilingsg',
    status: 'replied', batch_id: 'b4', batch_name: 'Series A Companies',
    assigned_to: 'u3', assigned_name: "Cara O'Brien", source: 'csv_import',
    last_activity_at: hoursAgo(6), created_at: daysAgo(5), updated_at: hoursAgo(6),
  },
  {
    id: 'l17', workspace_id: 'ws1',
    first_name: 'Carlos', last_name: 'Reyes', email: 'creyes@syncbridge.mx',
    phone: '+52 55 555 1717', company: 'SyncBridge', title: 'Founder & CTO',
    website: null, linkedin_url: null,
    status: 'new', batch_id: 'b2', batch_name: 'Inbound — March 2026',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: null, created_at: daysAgo(0), updated_at: daysAgo(0),
  },
  {
    id: 'l18', workspace_id: 'ws1',
    first_name: 'Fatima', last_name: 'Al-Rashid', email: 'fatima@novaops.sa',
    phone: '+966 55 555 1818', company: 'NovaOps', title: 'COO',
    website: 'https://novaops.sa', linkedin_url: null,
    status: 'interested', batch_id: 'b4', batch_name: 'Series A Companies',
    assigned_to: 'u2', assigned_name: 'Bob Tanaka', source: 'csv_import',
    last_activity_at: hoursAgo(1), created_at: daysAgo(9), updated_at: hoursAgo(1),
  },
  {
    id: 'l19', workspace_id: 'ws1',
    first_name: 'Jake', last_name: 'Morrison', email: 'jake@pipelinehq.us',
    phone: '+1 737 555 1919', company: 'PipelineHQ', title: 'CEO',
    website: 'https://pipelinehq.us', linkedin_url: 'https://linkedin.com/in/jakemorrison',
    status: 'contacted', batch_id: 'b1', batch_name: 'Q2 SaaS Founders',
    assigned_to: 'u3', assigned_name: "Cara O'Brien", source: 'csv_import',
    last_activity_at: daysAgo(2), created_at: daysAgo(11), updated_at: daysAgo(2),
  },
  {
    id: 'l20', workspace_id: 'ws1',
    first_name: 'Nora', last_name: 'Lindqvist', email: 'nora@edgeops.se',
    phone: '+46 8 555 2020', company: 'EdgeOps AB', title: 'VP Engineering',
    website: 'https://edgeops.se', linkedin_url: null,
    status: 'new', batch_id: 'b3', batch_name: 'Cold Outreach v1',
    assigned_to: 'u1', assigned_name: 'Alice Chen', source: 'csv_import',
    last_activity_at: null, created_at: daysAgo(1), updated_at: daysAgo(1),
  },
]
