import type { Campaign, CampaignWithSteps } from './types'

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id:                 'camp-1',
    workspace_id:       'ws-1',
    created_by:         'u1',
    name:               'Q2 SaaS Founder Outreach',
    description:        'Targeting SaaS founders from May import list',
    batch_id:           'batch-1',
    sending_account_id: 'acct-1',
    status:             'running',
    scheduled_start:    null,
    started_at:         '2026-05-01T08:00:00Z',
    completed_at:       null,
    paused_at:          null,
    total_leads:        248,
    emails_sent:        186,
    emails_opened:      73,
    emails_clicked:     24,
    emails_replied:     18,
    emails_bounced:     3,
    created_at:         '2026-04-28T10:00:00Z',
    updated_at:         '2026-05-07T08:30:00Z',
  },
  {
    id:                 'camp-2',
    workspace_id:       'ws-1',
    created_by:         'u1',
    name:               'Enterprise CTO Cold Sequence',
    description:        '3-step sequence for enterprise CTOs',
    batch_id:           'batch-2',
    sending_account_id: 'acct-2',
    status:             'paused',
    scheduled_start:    null,
    started_at:         '2026-04-15T08:00:00Z',
    completed_at:       null,
    paused_at:          '2026-04-22T14:00:00Z',
    total_leads:        120,
    emails_sent:        89,
    emails_opened:      30,
    emails_clicked:     9,
    emails_replied:     7,
    emails_bounced:     2,
    created_at:         '2026-04-10T09:00:00Z',
    updated_at:         '2026-04-22T14:00:00Z',
  },
  {
    id:                 'camp-3',
    workspace_id:       'ws-1',
    created_by:         'u2',
    name:               'May Follow-up Sequence',
    description:        null,
    batch_id:           'batch-3',
    sending_account_id: 'acct-1',
    status:             'draft',
    scheduled_start:    '2026-05-15T08:00:00Z',
    started_at:         null,
    completed_at:       null,
    paused_at:          null,
    total_leads:        0,
    emails_sent:        0,
    emails_opened:      0,
    emails_clicked:     0,
    emails_replied:     0,
    emails_bounced:     0,
    created_at:         '2026-05-06T15:00:00Z',
    updated_at:         '2026-05-06T15:00:00Z',
  },
  {
    id:                 'camp-4',
    workspace_id:       'ws-1',
    created_by:         'u1',
    name:               'Product Launch Blast',
    description:        'One-shot announcement to all active leads',
    batch_id:           'batch-4',
    sending_account_id: 'acct-1',
    status:             'completed',
    scheduled_start:    null,
    started_at:         '2026-03-20T08:00:00Z',
    completed_at:       '2026-03-21T18:00:00Z',
    paused_at:          null,
    total_leads:        315,
    emails_sent:        312,
    emails_opened:      148,
    emails_clicked:     62,
    emails_replied:     41,
    emails_bounced:     3,
    created_at:         '2026-03-18T11:00:00Z',
    updated_at:         '2026-03-21T18:00:00Z',
  },
]

export const MOCK_BATCHES = [
  { id: 'batch-1', name: 'May 2026 Import — SaaS',    lead_count: 248 },
  { id: 'batch-2', name: 'Enterprise CTOs Q1',        lead_count: 120 },
  { id: 'batch-3', name: 'Follow-up Pool May',        lead_count: 74  },
  { id: 'batch-4', name: 'Full Database March',       lead_count: 315 },
]

export const MOCK_ACCOUNT_OPTIONS = [
  { id: 'acct-1', name: 'Primary outreach',  from_email: 'alex@summits.io',    from_name: 'Alex from Summits', quota_remaining: 38, quota_percent: 24 },
  { id: 'acct-2', name: 'Follow-up account', from_email: 'support@summits.io', from_name: 'Support — Summits', quota_remaining: 6,  quota_percent: 88 },
]
