import type { Notification } from './types'

const now = new Date()
const mins = (n: number) => new Date(now.getTime() - n * 60_000).toISOString()
const hrs  = (n: number) => new Date(now.getTime() - n * 3_600_000).toISOString()

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1', workspace_id: 'w1', user_id: 'u1',
    type: 'reply_received',
    title: 'Sarah Chen replied to your email',
    body: '"Thanks for reaching out! I\'d love to schedule a call..."',
    link: '/leads/lead-1',
    is_read: false,
    lead_id: 'lead-1', email_id: 'email-1', campaign_id: null,
    created_at: mins(3),
  },
  {
    id: '2', workspace_id: 'w1', user_id: 'u1',
    type: 'follow_up_due',
    title: 'Follow-up due: Marcus Rodriguez',
    body: 'Scheduled follow-up is due today. He was interested in the enterprise plan.',
    link: '/leads/lead-2',
    is_read: false,
    lead_id: 'lead-2', email_id: null, campaign_id: null,
    created_at: mins(15),
  },
  {
    id: '3', workspace_id: 'w1', user_id: 'u1',
    type: 'quota_warning',
    title: 'Gmail Outreach is at 84% daily quota',
    body: '42/50 emails sent today. Consider pausing campaigns to save capacity.',
    link: '/settings/sending-accounts',
    is_read: false,
    lead_id: null, email_id: null, campaign_id: null,
    created_at: hrs(1),
  },
  {
    id: '4', workspace_id: 'w1', user_id: 'u1',
    type: 'lead_assigned',
    title: 'New lead assigned: Alex Kim',
    body: 'Michael assigned Alex Kim (Stripe) to you.',
    link: '/leads/lead-3',
    is_read: false,
    lead_id: 'lead-3', email_id: null, campaign_id: null,
    created_at: hrs(2),
  },
  {
    id: '5', workspace_id: 'w1', user_id: 'u1',
    type: 'campaign_complete',
    title: 'Campaign "Q2 Outreach" completed',
    body: '127 emails sent · 34% open rate · 8 replies received.',
    link: '/campaigns/c1',
    is_read: true,
    lead_id: null, email_id: null, campaign_id: 'c1',
    created_at: hrs(5),
  },
  {
    id: '6', workspace_id: 'w1', user_id: 'u1',
    type: 'bounce',
    title: 'Email bounced: james@oldcompany.io',
    body: 'Hard bounce — email address does not exist. Lead has been flagged.',
    link: '/leads/lead-4',
    is_read: true,
    lead_id: 'lead-4', email_id: 'email-5', campaign_id: null,
    created_at: hrs(8),
  },
  {
    id: '7', workspace_id: 'w1', user_id: 'u1',
    type: 'ai_batch_complete',
    title: 'AI personalisation complete',
    body: '48 personalized email drafts ready for "Series B SaaS Founders" campaign.',
    link: '/campaigns/c2',
    is_read: true,
    lead_id: null, email_id: null, campaign_id: 'c2',
    created_at: hrs(12),
  },
  {
    id: '8', workspace_id: 'w1', user_id: 'u1',
    type: 'follow_up_due',
    title: 'Follow-up due: Emma Wilson',
    body: 'You planned to follow up after she reviewed the pricing doc.',
    link: '/leads/lead-5',
    is_read: true,
    lead_id: 'lead-5', email_id: null, campaign_id: null,
    created_at: hrs(24),
  },
]
